apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-app
  labels:
    app: coupon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-app
  # POD BODY
  template:
    metadata:
      name: coupon-app
      labels:
        app: coupon-app
    # POD SPECS
    spec:
      containers:
        - name: coupon-app
          image: demiglace0505/couponservice
