apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  # REPLICAS SECTION
  replicas: 1
  selector:
    matchLabels:
      app: docker-mysql
  # POD TEMPLATE
  template:
    metadata:
      labels:
        app: docker-mysql
    # POD SPECS
    spec:
      volumes:
        - name: mysql-initdb-vol
          configMap:
            name: mysql-initdb-config
      containers:
        - name: docker-mysql
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-initdb-vol
              mountPath: /docker-entrypoint-initdb.d
