apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebserver
  labels:
    app: httpd
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: myhttpd
          image: httpd:2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: demovol
            - mountPath: /etc/config
              name: demo-configmap-vol
            - mountPath: /etc/mysecrets
              name: my-secret
            - mountPath: /data/clustervol
              name: demo-pvc
      volumes:
        - name: demovol
          hostPath:
            path: /data
            type: Directory
        - name: demo-configmap-vol
          configMap:
            name: demo-configmap
        - name: my-secret
          secret:
            secretName: demo-secret
        - name: demo-pvc
          persistentVolumeClaim:
            claimName: demo-pvc
